import { Product } from "./types";

export const CATERING_PRODUCTS: Product[] = [
  // --- MINI GOURMET DULCES ---
  {
    id: "catering-sweet-salted-caramel-brownie",
    name: "Salted Caramel Brownie",
    description: "Tierno y meloso bocado de brownie de cacao belga de la casa, bañado con finos hilos de caramelo salado fleur de sel de nuestra receta tradicional.",
    price: 1800,
    category: "catering",
    subcategory: "mini_gourmet_dulces",
    presentation: "Mini Gourmet aprox. 6 cm",
    minimumOrder: "9 unidades",
    pageNumber: 5,
    rating: 4.9,
    sizes: [{ label: "Mini Gourmet aprox. 6 cm", priceAdder: 0, servings: "Mínimo: 9 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_dulces/salted-caramel-brownie.jpg"
  },
  {
    id: "catering-sweet-salted-caramel-cheesecake",
    name: "Salted Caramel Cheesecake",
    description: "Base de galleta crujiente, crema densa y sedosa de queso, coronado con una generosa capa de caramelo salado artesanal horneado lentamente.",
    price: 1800,
    category: "catering",
    subcategory: "mini_gourmet_dulces",
    presentation: "Mini Gourmet aprox. 6 cm",
    minimumOrder: "16 unidades",
    pageNumber: 5,
    rating: 4.8,
    sizes: [{ label: "Mini Gourmet aprox. 6 cm", priceAdder: 0, servings: "Mínimo: 16 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_dulces/salted-caramel-cheesecake.jpg"
  },
  {
    id: "catering-sweet-cheesecake-rosas",
    name: "Cheesecake de Rosas",
    description: "Sutil e inolvidable receta de cheesecake infusionada con esencia natural de rosas orgánicas, decorada con pétalos finos.",
    price: 1800,
    category: "catering",
    subcategory: "mini_gourmet_dulces",
    presentation: "Mini Gourmet aprox. 6 cm",
    minimumOrder: "16 unidades",
    pageNumber: 5,
    rating: 4.9,
    sizes: [{ label: "Mini Gourmet aprox. 6 cm", priceAdder: 0, servings: "Mínimo: 16 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_dulces/cheesecake-de-rosas.jpg"
  },
  {
    id: "catering-sweet-strawberry-country-cake",
    name: "Strawberry Country Cake",
    description: "Bizcocho rústico de vainilla húmedo, alternado con capas delicadas de crema batida de pastura y fresas frescas seleccionadas de temporada.",
    price: 1800,
    category: "catering",
    subcategory: "mini_gourmet_dulces",
    presentation: "Mini Gourmet aprox. 6 cm",
    minimumOrder: "20 unidades",
    pageNumber: 7,
    rating: 4.8,
    sizes: [{ label: "Mini Gourmet aprox. 6 cm", priceAdder: 0, servings: "Mínimo: 20 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_dulces/strawberry-country-cake.jpg"
  },
  {
    id: "catering-sweet-banano-cheese-frosting",
    name: "Queque de Banano con Cheese Frosting",
    description: "Bizcocho aromático y tierno de banano maduro caramelizado, cubierto con un suntuoso y untuoso frosting de queso crema.",
    price: 1800,
    category: "catering",
    subcategory: "mini_gourmet_dulces",
    presentation: "Mini Gourmet aprox. 6 cm",
    minimumOrder: "20 unidades",
    pageNumber: 7,
    rating: 4.7,
    sizes: [{ label: "Mini Gourmet aprox. 6 cm", priceAdder: 0, servings: "Mínimo: 20 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_dulces/queque-de-banano-con-cheese-frosting.jpg"
  },
  {
    id: "catering-sweet-chocolate-pb",
    name: "Queque de Chocolate con Peanut Butter Cream",
    description: "Equilibrio supremo entre un intenso bizcocho de cacao premium y una sedosa crema batida de mantequilla de maní artesanal.",
    price: 1800,
    category: "catering",
    subcategory: "mini_gourmet_dulces",
    presentation: "Mini Gourmet aprox. 6 cm",
    minimumOrder: "20 unidades",
    pageNumber: 7,
    rating: 4.9,
    sizes: [{ label: "Mini Gourmet aprox. 6 cm", priceAdder: 0, servings: "Mínimo: 20 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_dulces/queque-de-chocolate-con-peanut-butter-cream.jpg"
  },
  {
    id: "catering-sweet-streusel-naranja",
    name: "Streusel de Naranja",
    description: "Masa húmeda con ralladura y néctar de naranja real, coronada con una costra dorada y crujiente de streusel de mantequilla y canela.",
    price: 1800,
    category: "catering",
    subcategory: "mini_gourmet_dulces",
    presentation: "Mini Gourmet aprox. 6 cm",
    minimumOrder: "15 unidades",
    pageNumber: 7,
    rating: 4.8,
    sizes: [{ label: "Mini Gourmet aprox. 6 cm", priceAdder: 0, servings: "Mínimo: 15 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_dulces/streusel-de-naranja.jpg"
  },
  {
    id: "catering-sweet-seco-naranja-chips",
    name: "Queque seco de naranja y chips de chocolate",
    description: "Receta tradicional de queque seco perfumada con aceites naturales de naranja y enriquecida con abundantes chispas de chocolate semiamargo.",
    price: 1800,
    category: "catering",
    subcategory: "mini_gourmet_dulces",
    presentation: "Mini Gourmet aprox. 6 cm",
    minimumOrder: "25 unidades",
    pageNumber: 7,
    rating: 4.7,
    sizes: [{ label: "Mini Gourmet aprox. 6 cm", priceAdder: 0, servings: "Mínimo: 25 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_dulces/queque-seco-de-naranja-y-chips-de-chocolate.jpg"
  },
  {
    id: "catering-sweet-roulade-uchuva",
    name: "Roulade de Vainilla relleno de Mousse de Uchuva",
    description: "Fino pionono de vainilla Bourbon enrollado con un exótico y refrescante mousse de uchuvas silvestres de nuestra campiña.",
    price: 1800,
    category: "catering",
    subcategory: "mini_gourmet_dulces",
    presentation: "Mini Gourmet aprox. 6 cm",
    minimumOrder: "20 unidades",
    pageNumber: 8,
    rating: 4.9,
    sizes: [{ label: "Mini Gourmet aprox. 6 cm", priceAdder: 0, servings: "Mínimo: 20 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_dulces/roulade-de-vainilla-relleno-de-mousse-de-uchuva.jpg"
  },
  {
    id: "catering-sweet-tentacion-choco",
    name: "Tentación de Chocolate",
    description: "La apoteosis del chocolate en formato bocado: capas alternas de pastel húmedo de chocolate y ganache sedoso de cacao belga.",
    price: 1800,
    category: "catering",
    subcategory: "mini_gourmet_dulces",
    presentation: "Mini Gourmet aprox. 6 cm",
    minimumOrder: "20 unidades",
    pageNumber: 8,
    rating: 4.9,
    sizes: [{ label: "Mini Gourmet aprox. 6 cm", priceAdder: 0, servings: "Mínimo: 20 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_dulces/tentacion-de-chocolate.jpg"
  },
  {
    id: "catering-sweet-payasam",
    name: "Payasam",
    description: "Inspiración oriental de pudding dulce de arroz con leche de cardamomo, azafrán, hilos de coco tostado y frutos secos selectos.",
    price: 1800,
    category: "catering",
    subcategory: "mini_gourmet_dulces",
    presentation: "Mini Gourmet aprox. 6 cm",
    minimumOrder: "20 unidades",
    pageNumber: 8,
    rating: 4.8,
    sizes: [{ label: "Mini Gourmet aprox. 6 cm", priceAdder: 0, servings: "Mínimo: 20 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_dulces/payasam.jpg"
  },
  {
    id: "catering-sweet-gajar-halwa",
    name: "Gajar Halwa Sunehri",
    description: "Exquisitez de la alta repostería india elaborada a base de zanahorias dulces cocidas en leche entera, ghee, almendras tostadas y cardamomo.",
    price: 1800,
    category: "catering",
    subcategory: "mini_gourmet_dulces",
    presentation: "Mini Gourmet aprox. 6 cm",
    minimumOrder: "25 unidades",
    pageNumber: 8,
    rating: 4.8,
    sizes: [{ label: "Mini Gourmet aprox. 6 cm", priceAdder: 0, servings: "Mínimo: 25 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_dulces/gajar-halwa-sunehri.jpg"
  },
  {
    id: "catering-sweet-tres-leches-coco",
    name: "Tres Leches de Coco",
    description: "Bizcochuelo empapado en nuestra mezcla secreta de tres leches enriquecida con crema de coco real, decorado con merengue y copos tostados.",
    price: 1800,
    category: "catering",
    subcategory: "mini_gourmet_dulces",
    presentation: "Mini Gourmet aprox. 6 cm",
    minimumOrder: "30 unidades",
    pageNumber: 8,
    rating: 4.9,
    sizes: [{ label: "Mini Gourmet aprox. 6 cm", priceAdder: 0, servings: "Mínimo: 30 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_dulces/tres-leches-de-coco.jpg"
  },
  {
    id: "catering-sweet-pudding-arroz-ron",
    name: "Pudding de Arroz con Ron",
    description: "Clásico pudding de arroz cremoso cocinado lentamente a fuego bajo, perfumado con canela de Ceilán y un toque de ron añejo costarricense.",
    price: 1800,
    category: "catering",
    subcategory: "mini_gourmet_dulces",
    presentation: "Mini Gourmet aprox. 6 cm",
    minimumOrder: "20 unidades",
    pageNumber: 8,
    rating: 4.8,
    sizes: [{ label: "Mini Gourmet aprox. 6 cm", priceAdder: 0, servings: "Mínimo: 20 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_dulces/pudding-de-arroz-con-ron.jpg"
  },
  {
    id: "catering-sweet-panna-cotta-choco",
    name: "Panna Cotta de Chocolate con Fresas al Grand Marnier",
    description: "Crema italiana cocida de chocolate belga de alta pureza, servida con un coulis fresco de fresas maceradas en licor de naranja Grand Marnier.",
    price: 1800,
    category: "catering",
    subcategory: "mini_gourmet_dulces",
    presentation: "Mini Gourmet aprox. 6 cm",
    minimumOrder: "25 unidades",
    pageNumber: 9,
    rating: 4.9,
    sizes: [{ label: "Mini Gourmet aprox. 6 cm", priceAdder: 0, servings: "Mínimo: 25 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_dulces/panna-cotta-de-chocolate-con-fresas-al-grand-marnier.jpg"
  },
  {
    id: "catering-sweet-suspiro-limeno",
    name: "Suspiro Limeño",
    description: "Postre tradicional peruano de manjar blanco de yemas cremoso, coronado con un copo de merengue italiano al oporto y canela espolvoreada.",
    price: 1800,
    category: "catering",
    subcategory: "mini_gourmet_dulces",
    presentation: "Mini Gourmet aprox. 6 cm",
    minimumOrder: "20 unidades",
    pageNumber: 9,
    rating: 4.9,
    sizes: [{ label: "Mini Gourmet aprox. 6 cm", priceAdder: 0, servings: "Mínimo: 20 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_dulces/suspiro-limeno.jpg"
  },
  {
    id: "catering-sweet-pudding-arroz-baileys",
    name: "Pudding de Arroz con Baileys",
    description: "Nuestra suntuosa crema de arroz con leche combinada en su punto exacto con la dulzura y el licor característicos de la crema de whisky Baileys.",
    price: 1800,
    category: "catering",
    subcategory: "mini_gourmet_dulces",
    presentation: "Mini Gourmet aprox. 6 cm",
    minimumOrder: "30 unidades",
    pageNumber: 9,
    rating: 4.8,
    sizes: [{ label: "Mini Gourmet aprox. 6 cm", priceAdder: 0, servings: "Mínimo: 30 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_dulces/pudding-de-arroz-con-baileys.jpg"
  },
  {
    id: "catering-sweet-zabaglione",
    name: "Zabaglione",
    description: "Postre tradicional italiano de sabayón batido en caliente con yemas frescas, azúcar de caña fina y el toque aromático del vino Marsala.",
    price: 1800,
    category: "catering",
    subcategory: "mini_gourmet_dulces",
    presentation: "Mini Gourmet aprox. 6 cm",
    minimumOrder: "20 unidades",
    pageNumber: 9,
    rating: 4.7,
    sizes: [{ label: "Mini Gourmet aprox. 6 cm", priceAdder: 0, servings: "Mínimo: 20 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_dulces/zabaglione.jpg"
  },
  {
    id: "catering-sweet-eton-mess",
    name: "Eton Mess",
    description: "Delicioso desorden británico tradicional elaborado con trozos crujientes de merengue artesanal de vainilla, fresas ácidas y crema de leche batida.",
    price: 1800,
    category: "catering",
    subcategory: "mini_gourmet_dulces",
    presentation: "Mini Gourmet aprox. 6 cm",
    minimumOrder: "15 unidades",
    pageNumber: 9,
    rating: 4.8,
    sizes: [{ label: "Mini Gourmet aprox. 6 cm", priceAdder: 0, servings: "Mínimo: 15 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_dulces/eton-mess.jpg"
  },
  {
    id: "catering-sweet-panna-cotta-vainilla",
    name: "Panna Cotta de Vainilla con Fresas al Grand Marnier",
    description: "Panna cotta cremosa e hiper-suave con semillas de vainilla Bourbon de Madagascar, cubierta de fresas selectas al licor Grand Marnier.",
    price: 1800,
    category: "catering",
    subcategory: "mini_gourmet_dulces",
    presentation: "Mini Gourmet aprox. 6 cm",
    minimumOrder: "30 unidades",
    pageNumber: 9,
    rating: 4.9,
    sizes: [{ label: "Mini Gourmet aprox. 6 cm", priceAdder: 0, servings: "Mínimo: 30 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_dulces/panna-cotta-de-vainilla-con-fresas-al-grand-marnier.jpg"
  },
  {
    id: "catering-sweet-mousse-limon",
    name: "Mousse de Limón",
    description: "Crema aireada de limón real, ligera y refrescante, con un balance perfecto entre dulzura y acidez cítrica.",
    price: 1800,
    category: "catering",
    subcategory: "mini_gourmet_dulces",
    presentation: "Mini Gourmet aprox. 6 cm",
    minimumOrder: "25 unidades",
    pageNumber: 10,
    rating: 4.8,
    sizes: [{ label: "Mini Gourmet aprox. 6 cm", priceAdder: 0, servings: "Mínimo: 25 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_dulces/mousse-de-limon.jpg"
  },
  {
    id: "catering-sweet-mousse-maracuya",
    name: "Mousse de Maracuyá con Mango",
    description: "Mousse tropical sedoso elaborado con pulpa pura de maracuyá y un centro dulce de jalea coulis de mango maduro de la zona.",
    price: 1800,
    category: "catering",
    subcategory: "mini_gourmet_dulces",
    presentation: "Mini Gourmet aprox. 6 cm",
    minimumOrder: "20 unidades",
    pageNumber: 10,
    rating: 4.9,
    sizes: [{ label: "Mini Gourmet aprox. 6 cm", priceAdder: 0, servings: "Mínimo: 20 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_dulces/mousse-de-maracuya-con-mango.jpg"
  },
  {
    id: "catering-sweet-pudding-choco",
    name: "Pudding de Chocolate",
    description: "Crema densa de chocolate elaborada con un blend de cacao nacional al 65% de pureza, cocinada a fuego lento con leche entera.",
    price: 1800,
    category: "catering",
    subcategory: "mini_gourmet_dulces",
    presentation: "Mini Gourmet aprox. 6 cm",
    minimumOrder: "30 unidades",
    pageNumber: 10,
    rating: 4.8,
    sizes: [{ label: "Mini Gourmet aprox. 6 cm", priceAdder: 0, servings: "Mínimo: 30 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_dulces/pudding-de-chocolate.jpg"
  },
  {
    id: "catering-sweet-pie-limon",
    name: "Pie de Limón",
    description: "Base crujiente de galleta de mantequilla, relleno cremoso y ácido de limón real y un tierno copo de merengue tostado al soplete.",
    price: 1800,
    category: "catering",
    subcategory: "mini_gourmet_dulces",
    presentation: "Mini Gourmet aprox. 6 cm",
    minimumOrder: "15 unidades",
    pageNumber: 10,
    rating: 4.9,
    sizes: [{ label: "Mini Gourmet aprox. 6 cm", priceAdder: 0, servings: "Mínimo: 15 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_dulces/pie-de-limon.jpg"
  },
  {
    id: "catering-sweet-pie-pumpkin",
    name: "Pie de Pumpkin con Banano",
    description: "Increíble y aromática tarta rústica que fusiona el puré de calabaza especiado y la dulzura caramelizada del banano maduro horneado.",
    price: 1800,
    category: "catering",
    subcategory: "mini_gourmet_dulces",
    presentation: "Mini Gourmet aprox. 6 cm",
    minimumOrder: "20 unidades",
    pageNumber: 10,
    rating: 4.8,
    sizes: [{ label: "Mini Gourmet aprox. 6 cm", priceAdder: 0, servings: "Mínimo: 20 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_dulces/pie-de-pumkin-con-banano.jpg"
  },
  {
    id: "catering-sweet-mousse-choco-marnier",
    name: "Mousse de Chocolate con Grand Marnier",
    description: "Textura hiper-aireada de puro chocolate amargo belga al 70%, aromatizado elegantemente con licor de naranja francés Grand Marnier.",
    price: 1800,
    category: "catering",
    subcategory: "mini_gourmet_dulces",
    presentation: "Mini Gourmet aprox. 6 cm",
    minimumOrder: "30 unidades",
    pageNumber: 10,
    rating: 4.9,
    sizes: [{ label: "Mini Gourmet aprox. 6 cm", priceAdder: 0, servings: "Mínimo: 30 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_dulces/mousse-de-chocolate-con-grand-marnier.jpg"
  },
  {
    id: "catering-sweet-mousse-pistacho",
    name: "Mousse de Pistachos",
    description: "Lujoso y aterciopelado mousse elaborado a base de auténtico praliné y pasta de pistachos molidos de Bronte, Sicilia.",
    price: 1800,
    category: "catering",
    subcategory: "mini_gourmet_dulces",
    presentation: "Mini Gourmet aprox. 6 cm",
    minimumOrder: "20 unidades",
    pageNumber: 11,
    rating: 4.9,
    sizes: [{ label: "Mini Gourmet aprox. 6 cm", priceAdder: 0, servings: "Mínimo: 20 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_dulces/mousse-de-pistachos.jpg"
  },
  {
    id: "catering-sweet-bundt-limon-amapola",
    name: "Bundt Cakes de Limón con semillas de amapola",
    description: "Minis de queque bundt de limón real súper húmedos, salpicados de crujientes semillas de amapola y bañados en un glaseado traslúcido.",
    price: 1800,
    category: "catering",
    subcategory: "mini_gourmet_dulces",
    presentation: "Mini Gourmet aprox. 6 cm",
    minimumOrder: "20 unidades",
    pageNumber: 11,
    rating: 4.8,
    sizes: [{ label: "Mini Gourmet aprox. 6 cm", priceAdder: 0, servings: "Mínimo: 20 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_dulces/bundt-cakes-de-limon-con-semillas-de-amapola.jpg"
  },
  {
    id: "catering-sweet-bundt-choco-nueces",
    name: "Bundt Cakes de Chocolate con nueces y chips de chocolate",
    description: "Minis de queque bundt de chocolate denso elaborados con cacao belga, rellenos de nueces picadas y chips de chocolate.",
    price: 1800,
    category: "catering",
    subcategory: "mini_gourmet_dulces",
    presentation: "Mini Gourmet aprox. 6 cm",
    minimumOrder: "20 unidades",
    pageNumber: 11,
    rating: 4.8,
    sizes: [{ label: "Mini Gourmet aprox. 6 cm", priceAdder: 0, servings: "Mínimo: 20 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_dulces/bundt-cakes-de-chocolate-con-nueces-y-chips-de-chocolate.jpg"
  },
  {
    id: "catering-sweet-bundt-cafe-caramelo",
    name: "Bundt Cakes de Café con glaze de caramelo y pecanas",
    description: "Esponjoso mini bundt enriquecido con infusión de café espresso costarricense, bañado en un dulce glaze de toffee de caramelo y pecanas tostadas.",
    price: 1800,
    category: "catering",
    subcategory: "mini_gourmet_dulces",
    presentation: "Mini Gourmet aprox. 6 cm",
    minimumOrder: "20 unidades",
    pageNumber: 11,
    rating: 4.9,
    sizes: [{ label: "Mini Gourmet aprox. 6 cm", priceAdder: 0, servings: "Mínimo: 20 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_dulces/bundt-cakes-de-cafe-con-glaze-de-caramelo-y-pecanas.jpg"
  },
  {
    id: "catering-sweet-bundt-naranja",
    name: "Bundt Cakes de Naranja",
    description: "Pura frescura cítrica hecha queque. Mini bundt súper tierno elaborado con ralladura de naranja dulce y bañado en almíbar cítrico templado.",
    price: 1800,
    category: "catering",
    subcategory: "mini_gourmet_dulces",
    presentation: "Mini Gourmet aprox. 6 cm",
    minimumOrder: "20 unidades",
    pageNumber: 11,
    rating: 4.8,
    sizes: [{ label: "Mini Gourmet aprox. 6 cm", priceAdder: 0, servings: "Mínimo: 20 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_dulces/bundt-cakes-de-naranja.jpg"
  },
  {
    id: "catering-sweet-bundt-naranja-chips",
    name: "Bundt Cakes de Naranja y Chips de Chocolate",
    description: "El maridaje clásico perfeccionado: tierno bizcocho de naranja con abundantes chispas crujientes de chocolate belga semiamargo.",
    price: 1800,
    category: "catering",
    subcategory: "mini_gourmet_dulces",
    presentation: "Mini Gourmet aprox. 6 cm",
    minimumOrder: "20 unidades",
    pageNumber: 11,
    rating: 4.8,
    sizes: [{ label: "Mini Gourmet aprox. 6 cm", priceAdder: 0, servings: "Mínimo: 20 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_dulces/bundt-cakes-de-naranja-y-chips-de-chocolate.jpg"
  },
  {
    id: "catering-sweet-tri-avellana",
    name: "Trí de Avellana",
    description: "Sinfonía imperial de tres capas de mousse y cremas finas a base de avellanas tostadas europeas y gianduja de chocolate con avellanas.",
    price: 2500,
    category: "catering",
    subcategory: "mini_gourmet_dulces",
    presentation: "Mini Gourmet aprox. 6 cm",
    minimumOrder: "20 unidades",
    pageNumber: 12,
    rating: 5.0,
    sizes: [{ label: "Mini Gourmet aprox. 6 cm", priceAdder: 0, servings: "Mínimo: 20 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_dulces/tri-de-avellana.jpg"
  },
  {
    id: "catering-sweet-tiramisu-baileys",
    name: "Tiramisú de Chocolate y Baileys",
    description: "Nuestra reinterpretación del tiramisú de café con capas de bizcocho remojado en espresso, crema rica de mascarpone y un generoso chorro de Baileys.",
    price: 2500,
    category: "catering",
    subcategory: "mini_gourmet_dulces",
    presentation: "Mini Gourmet aprox. 6 cm",
    minimumOrder: "20 unidades",
    pageNumber: 12,
    rating: 5.0,
    sizes: [{ label: "Mini Gourmet aprox. 6 cm", priceAdder: 0, servings: "Mínimo: 20 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_dulces/tiramisu-de-chocolate-y-baileys.jpg"
  },
  {
    id: "catering-sweet-roulade-calabaza",
    name: "Roulade de Calabaza",
    description: "Bizcocho tierno de puré de calabaza asada y especias de otoño, enrollado con un aterciopelado frosting artesanal de queso crema premium.",
    price: 2500,
    category: "catering",
    subcategory: "mini_gourmet_dulces",
    presentation: "Mini Gourmet aprox. 6 cm",
    minimumOrder: "20 unidades",
    pageNumber: 12,
    rating: 4.9,
    sizes: [{ label: "Mini Gourmet aprox. 6 cm", priceAdder: 0, servings: "Mínimo: 20 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_dulces/roulade-de-calabaza.jpg"
  },
  {
    id: "catering-sweet-tiramisu-ron",
    name: "Tiramisú de Ron",
    description: "Postre cremoso de bizcochuelo remojado en café espresso de altura cargado con ron añejo, alternado con crema mascarpone batida a punto de nieve.",
    price: 2500,
    category: "catering",
    subcategory: "mini_gourmet_dulces",
    presentation: "Mini Gourmet aprox. 6 cm",
    minimumOrder: "20 unidades",
    pageNumber: 12,
    rating: 4.9,
    sizes: [{ label: "Mini Gourmet aprox. 6 cm", priceAdder: 0, servings: "Mínimo: 20 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_dulces/tiramisu-de-ron.jpg"
  },
  {
    id: "catering-sweet-trifle-fresa-arandano",
    name: "Trifle de Fresas y Arándanos",
    description: "Presentado en un elegante vasito: capas perfectas de bizcocho de vainilla, crema pastelera sedosa y compota de frutos del bosque.",
    price: 2500,
    category: "catering",
    subcategory: "mini_gourmet_dulces",
    presentation: "Mini Gourmet aprox. 6 cm",
    minimumOrder: "30 unidades",
    pageNumber: 12,
    rating: 4.9,
    sizes: [{ label: "Mini Gourmet aprox. 6 cm", priceAdder: 0, servings: "Mínimo: 30 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_dulces/trifle-de-fresas-y-arandanos.jpg"
  },
  {
    id: "catering-sweet-fantasia-limoncello",
    name: "Fantasía de Limoncello",
    description: "Delicada propuesta de bizcocho tierno humedecido en licor cremoso Limoncello italiano con un refrescante y sedoso mousse de limón real.",
    price: 2500,
    category: "catering",
    subcategory: "mini_gourmet_dulces",
    presentation: "Mini Gourmet aprox. 6 cm",
    minimumOrder: "20 unidades",
    pageNumber: 12,
    rating: 5.0,
    sizes: [{ label: "Mini Gourmet aprox. 6 cm", priceAdder: 0, servings: "Mínimo: 20 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_dulces/fantasia-de-limoncello.jpg"
  },
  {
    id: "catering-sweet-scones-choco-pecanas",
    name: "Scones de Chocolate con Pecanas",
    description: "Scones de estilo británico tradicional horneados a mano con hilos de chocolate amargo y trozos crujientes de pecanas tostadas.",
    price: 1800,
    category: "catering",
    subcategory: "mini_gourmet_dulces",
    presentation: "Mini Gourmet aprox. 6 cm",
    minimumOrder: "30 unidades",
    pageNumber: 13,
    rating: 4.8,
    sizes: [{ label: "Mini Gourmet aprox. 6 cm", priceAdder: 0, servings: "Mínimo: 30 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_dulces/scones-de-chocolate-con-pecanas.jpg"
  },
  {
    id: "catering-sweet-scones-cranberry",
    name: "Scones de Cranberry y Naranja",
    description: "Equilibrio británico entre la frescura cítrica de la naranja real y el contraste ácido de los arándanos deshidratados (cranberries).",
    price: 1800,
    category: "catering",
    subcategory: "mini_gourmet_dulces",
    presentation: "Mini Gourmet aprox. 6 cm",
    minimumOrder: "30 unidades",
    pageNumber: 13,
    rating: 4.8,
    sizes: [{ label: "Mini Gourmet aprox. 6 cm", priceAdder: 0, servings: "Mínimo: 30 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_dulces/scones-de-cranberry-y-naranja.jpg"
  },
  {
    id: "catering-sweet-barras-pecanas",
    name: "Barras de Pecanas",
    description: "Masa sablé de mantequilla, horneada con un toffee cremoso cargado de abundantes pecanas tostadas premium.",
    price: 1800,
    category: "catering",
    subcategory: "mini_gourmet_dulces",
    presentation: "Mini Gourmet aprox. 6 cm",
    minimumOrder: "40 unidades",
    pageNumber: 13,
    rating: 4.9,
    sizes: [{ label: "Mini Gourmet aprox. 6 cm", priceAdder: 0, servings: "Mínimo: 40 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_dulces/barras-de-pecanas.jpg"
  },
  {
    id: "catering-sweet-barras-mani-jalea",
    name: "Barras de Maní rellenas con jalea de frutos rojos",
    description: "Deliciosas barras de sándwich rellenas de mantequilla de maní cremosa y jalea coulis artesanal de frutos del bosque.",
    price: 1800,
    category: "catering",
    subcategory: "mini_gourmet_dulces",
    presentation: "Mini Gourmet aprox. 6 cm",
    minimumOrder: "40 unidades",
    pageNumber: 13,
    rating: 4.8,
    sizes: [{ label: "Mini Gourmet aprox. 6 cm", priceAdder: 0, servings: "Mínimo: 40 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_dulces/barras-de-mani-rellenas-con-jalea-de-frutos-rojos.jpg"
  },
  {
    id: "catering-sweet-barras-cranberry-coco",
    name: "Barras de Cranberries con coco y pecanas",
    description: "Barras energéticas gourmet cargadas de arándanos jugosos, coco rallado tostado a mano y pecanas seleccionadas.",
    price: 1800,
    category: "catering",
    subcategory: "mini_gourmet_dulces",
    presentation: "Mini Gourmet aprox. 6 cm",
    minimumOrder: "30 unidades",
    pageNumber: 13,
    rating: 4.8,
    sizes: [{ label: "Mini Gourmet aprox. 6 cm", priceAdder: 0, servings: "Mínimo: 30 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_dulces/barras-de-cranberries-con-coco-y-pecanas.jpg"
  },
  {
    id: "catering-sweet-barras-hawaianas",
    name: "Barras Hawaianas, coco y macadamia",
    description: "Exótica propuesta tropical de barras con base de galleta de mantequilla, coco caramelizado y nueces crujientes de macadamia.",
    price: 1800,
    category: "catering",
    subcategory: "mini_gourmet_dulces",
    presentation: "Mini Gourmet aprox. 6 cm",
    minimumOrder: "35 unidades",
    pageNumber: 13,
    rating: 4.9,
    sizes: [{ label: "Mini Gourmet aprox. 6 cm", priceAdder: 0, servings: "Mínimo: 35 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_dulces/barras-hawaianas-coco-y-macadamia.jpg"
  },
  {
    id: "catering-sweet-alfajores-maicena",
    name: "Alfajores de Maicena con dulce de leche",
    description: "Clásicos alfajores de masa de maicena sumamente tierna e hilada que se deshace en boca, rellenos de generoso dulce de leche repostero.",
    price: 1800,
    category: "catering",
    subcategory: "mini_gourmet_dulces",
    presentation: "Mini Gourmet aprox. 6 cm",
    minimumOrder: "20 unidades",
    pageNumber: 14,
    rating: 4.9,
    sizes: [{ label: "Mini Gourmet aprox. 6 cm", priceAdder: 0, servings: "Mínimo: 20 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_dulces/alfajores-de-maicena-con-dulce-de-leche.jpg"
  },
  {
    id: "catering-sweet-cupcakes-choco",
    name: "Cupcakes de Chocolate",
    description: "Esponjosos cupcakes de chocolate elaborados con cacao amargo de primera calidad, coronados con un rosetón de frosting trufado de chocolate.",
    price: 1800,
    category: "catering",
    subcategory: "mini_gourmet_dulces",
    presentation: "Mini Gourmet aprox. 6 cm",
    minimumOrder: "20 unidades",
    pageNumber: 14,
    rating: 4.8,
    sizes: [{ label: "Mini Gourmet aprox. 6 cm", priceAdder: 0, servings: "Mínimo: 20 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_dulces/cupcakes-de-chocolate.jpg"
  },
  {
    id: "catering-sweet-blondies-pecanas",
    name: "Blondies de pecanas",
    description: "Exquisitos blondies horneados a fuego lento, con hilos de azúcar morena de caña caramelizada y trozos de pecanas crujientes tostadas.",
    price: 1600,
    category: "catering",
    subcategory: "mini_gourmet_dulces",
    presentation: "Mini Gourmet aprox. 6 cm",
    minimumOrder: "30 unidades",
    pageNumber: 15,
    rating: 4.8,
    sizes: [{ label: "Mini Gourmet aprox. 6 cm", priceAdder: 0, servings: "Mínimo: 30 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_dulces/blondies-de-pecanas.jpg"
  },
  {
    id: "catering-sweet-tartaletas-macadamia",
    name: "Tartaletas de Macadamia, coco y chips de chocolate",
    description: "Pequeñas tartaletas rellenas con un dulce toffee artesanal, nueces de macadamia costarricense, ralladura de coco y chispas de chocolate.",
    price: 1600,
    category: "catering",
    subcategory: "mini_gourmet_dulces",
    presentation: "Mini Gourmet aprox. 6 cm",
    minimumOrder: "25 unidades",
    pageNumber: 15,
    rating: 4.9,
    sizes: [{ label: "Mini Gourmet aprox. 6 cm", priceAdder: 0, servings: "Mínimo: 25 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_dulces/tartaletas-de-macadamia-coco-y-chips-de-chocolate.jpg"
  },
  {
    id: "catering-sweet-mini-alfajores",
    name: "Mini Alfajores de Maicena con dulce de leche",
    description: "Versión de un solo bocado de nuestros afamados alfajores de maicena, con un tierno relleno de dulce de leche repostero.",
    price: 1600,
    category: "catering",
    subcategory: "mini_gourmet_dulces",
    presentation: "Mini Gourmet aprox. 6 cm",
    minimumOrder: "25 unidades",
    pageNumber: 15,
    rating: 4.9,
    sizes: [{ label: "Mini Gourmet aprox. 6 cm", priceAdder: 0, servings: "Mínimo: 25 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_dulces/mini-alfajores-de-maicena-con-dulce-de-leche.jpg"
  },
  {
    id: "catering-sweet-extravagante-brownie",
    name: "Extravagante Brownie con nueces y chips de chocolate",
    description: "Brownie de textura densa elaborado con un blend de cacao costarricense, cargado de crujientes nueces picadas y chispas de chocolate.",
    price: 1600,
    category: "catering",
    subcategory: "mini_gourmet_dulces",
    presentation: "Mini Gourmet aprox. 6 cm",
    minimumOrder: "20 unidades",
    pageNumber: 15,
    rating: 4.9,
    sizes: [{ label: "Mini Gourmet aprox. 6 cm", priceAdder: 0, servings: "Mínimo: 20 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_dulces/extravagante-brownie-con-nueces-y-chips-de-chocolate.jpg"
  },

  // --- MINI GOURMET COOKIES ---
  {
    id: "catering-cookie-macaroons-coco",
    name: "Macaroons de Coco",
    description: "Clásicas galletas rústicas e hiper-húmedas elaboradas puramente con claras de huevo batidas, coco rallado selecto y un almíbar suave horneado.",
    price: 1500,
    category: "catering",
    subcategory: "mini_gourmet_cookies",
    presentation: "Macaroon",
    minimumOrder: "15 unidades",
    pageNumber: 17,
    rating: 4.8,
    sizes: [{ label: "Macaroon", priceAdder: 0, servings: "Mínimo: 15 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_cookies/macaroons-de-coco.jpg"
  },

  // --- BRIGADEIROS BRASILEÑOS ---
  {
    id: "catering-brigadeiro-chocolate",
    name: "Brigadeiro Chocolate",
    description: "La trufa clásica brasileña por excelencia: dulce de chocolate cocinado lentamente, boleado a mano y cubierto con virutas de chocolate.",
    price: 1100,
    category: "catering",
    subcategory: "brigadeiros",
    presentation: "Brigadeiro",
    minimumOrder: "30 unidades",
    pageNumber: 18,
    rating: 4.9,
    sizes: [{ label: "Brigadeiro", priceAdder: 0, servings: "Mínimo: 30 unidades" }],
    image: "/src/assets/images/queques/menu_general/brigadeiros/brigadeiro-chocolate.jpg"
  },
  {
    id: "catering-brigadeiro-chocolate-blanco",
    name: "Brigadeiro Chocolate Blanco",
    description: "Delicada trufa brasileña cocinada a base de leche condensada premium y chocolate belga blanco, boleada y decorada finamente.",
    price: 1100,
    category: "catering",
    subcategory: "brigadeiros",
    presentation: "Brigadeiro",
    minimumOrder: "30 unidades",
    pageNumber: 18,
    rating: 4.8,
    sizes: [{ label: "Brigadeiro", priceAdder: 0, servings: "Mínimo: 30 unidades" }],
    image: "/src/assets/images/queques/menu_general/brigadeiros/brigadeiro-chocolate-blanco.jpg"
  },
  {
    id: "catering-brigadeiro-chocolate-relleno-coco",
    name: "Brigadeiro Chocolate con Relleno de Coco",
    description: "Increíble y tradicional combinación de trufa brasileña de chocolate con un corazón suave y jugoso de crema de coco.",
    price: 1100,
    category: "catering",
    subcategory: "brigadeiros",
    presentation: "Brigadeiro",
    minimumOrder: "30 unidades",
    pageNumber: 18,
    rating: 4.9,
    sizes: [{ label: "Brigadeiro", priceAdder: 0, servings: "Mínimo: 30 unidades" }],
    image: "/src/assets/images/queques/menu_general/brigadeiros/brigadeiro-chocolate-con-relleno-de-coco.jpg"
  },
  {
    id: "catering-brigadeiro-churchill",
    name: "Brigadeiro Churchill",
    description: "Tributo local y creativo: brigadeiro cremoso sabor de helado de Churchill costarricense con sirop, leche condensada y leche en polvo.",
    price: 1100,
    category: "catering",
    subcategory: "brigadeiros",
    presentation: "Brigadeiro",
    minimumOrder: "30 unidades",
    pageNumber: 18,
    rating: 4.9,
    sizes: [{ label: "Brigadeiro", priceAdder: 0, servings: "Mínimo: 30 unidades" }],
    image: "/src/assets/images/queques/menu_general/brigadeiros/brigadeiro-churchill.jpg"
  },
  {
    id: "catering-brigadeiro-churros",
    name: "Brigadeiro Churros",
    description: "Deliciosa trufa con canela de Ceilán molida fina y un corazón tierno de dulce de leche, cubierto con azúcar y canela.",
    price: 1100,
    category: "catering",
    subcategory: "brigadeiros",
    presentation: "Brigadeiro",
    minimumOrder: "30 unidades",
    pageNumber: 18,
    rating: 4.8,
    sizes: [{ label: "Brigadeiro", priceAdder: 0, servings: "Mínimo: 30 unidades" }],
    image: "/src/assets/images/queques/menu_general/brigadeiros/brigadeiro-churros.jpg"
  },
  {
    id: "catering-brigadeiro-coco",
    name: "Brigadeiro Coco",
    description: "Denominado Beijinho de Coco en Brasil. Trufa de leche condensada and coco rallado cocida a fuego lento y boleada en azúcar o coco rallado.",
    price: 1100,
    category: "catering",
    subcategory: "brigadeiros",
    presentation: "Brigadeiro",
    minimumOrder: "30 unidades",
    pageNumber: 18,
    rating: 4.9,
    sizes: [{ label: "Brigadeiro", priceAdder: 0, servings: "Mínimo: 30 unidades" }],
    image: "/src/assets/images/queques/menu_general/brigadeiros/brigadeiro-coco.jpg"
  },
  {
    id: "catering-brigadeiro-coco-albaricoque",
    name: "Brigadeiro Coco con Albaricoque",
    description: "Unión perfecta entre la trufa dulce de coco brasileña y una fina jalea cítrica y dulce de albaricoque seco importado.",
    price: 1100,
    category: "catering",
    subcategory: "brigadeiros",
    presentation: "Brigadeiro",
    minimumOrder: "30 unidades",
    pageNumber: 18,
    rating: 4.8,
    sizes: [{ label: "Brigadeiro", priceAdder: 0, servings: "Mínimo: 30 unidades" }],
    image: "/src/assets/images/queques/menu_general/brigadeiros/brigadeiro-coco-con-albaricoque.jpg"
  },
  {
    id: "catering-brigadeiro-coco-ciruela",
    name: "Brigadeiro Coco con Ciruela",
    description: "El maridaje tradicional brasileño conocido como 'Olho de Sogra': bocado delicioso de coco tierno cocido combinado con ciruela pasa jugosa.",
    price: 1100,
    category: "catering",
    subcategory: "brigadeiros",
    presentation: "Brigadeiro",
    minimumOrder: "30 unidades",
    pageNumber: 18,
    rating: 4.8,
    sizes: [{ label: "Brigadeiro", priceAdder: 0, servings: "Mínimo: 30 unidades" }],
    image: "/src/assets/images/queques/menu_general/brigadeiros/brigadeiro-coco-con-ciruela.jpg"
  },
  {
    id: "catering-brigadeiro-coco-higos",
    name: "Brigadeiro Coco con Higos",
    description: "Inspiradora trufa de coco en su punto exacto, enriquecida con tiernos y finos trozos de higos confitados en almíbar.",
    price: 1100,
    category: "catering",
    subcategory: "brigadeiros",
    presentation: "Brigadeiro",
    minimumOrder: "30 unidades",
    pageNumber: 18,
    rating: 4.7,
    sizes: [{ label: "Brigadeiro", priceAdder: 0, servings: "Mínimo: 30 unidades" }],
    image: "/src/assets/images/queques/menu_general/brigadeiros/brigadeiro-coco-con-higos.jpg"
  },
  {
    id: "catering-brigadeiro-dulce-leche",
    name: "Brigadeiro Dulce de Leche",
    description: "Tierno bocado de dulce de leche cocinado lentamente hasta lograr una textura masticable e hiper-untuosa, boleado a mano.",
    price: 1100,
    category: "catering",
    subcategory: "brigadeiros",
    presentation: "Brigadeiro",
    minimumOrder: "30 unidades",
    pageNumber: 18,
    rating: 4.9,
    sizes: [{ label: "Brigadeiro", priceAdder: 0, servings: "Mínimo: 30 unidades" }],
    image: "/src/assets/images/queques/menu_general/brigadeiros/brigadeiro-dulce-de-leche.jpg"
  },
  {
    id: "catering-brigadeiro-dulce-leche-coco",
    name: "Brigadeiro Dulce de Leche con Coco",
    description: "Dos clásicos unidos a fuego bajo: dulce de leche repostero untuoso cocinado con coco rallado de temporada.",
    price: 1100,
    category: "catering",
    subcategory: "brigadeiros",
    presentation: "Brigadeiro",
    minimumOrder: "30 unidades",
    pageNumber: 18,
    rating: 4.8,
    sizes: [{ label: "Brigadeiro", priceAdder: 0, servings: "Mínimo: 30 unidades" }],
    image: "/src/assets/images/queques/menu_general/brigadeiros/brigadeiro-dulce-de-leche-con-coco.jpg"
  },
  {
    id: "catering-brigadeiro-fresa",
    name: "Brigadeiro Fresa",
    description: "Conocido en Brasil como 'Bicho de Pé'. Trufa brasileña elaborada con un almíbar dulce de fresas selectas de temporada.",
    price: 1100,
    category: "catering",
    subcategory: "brigadeiros",
    presentation: "Brigadeiro",
    minimumOrder: "30 unidades",
    pageNumber: 18,
    rating: 4.8,
    sizes: [{ label: "Brigadeiro", priceAdder: 0, servings: "Mínimo: 30 unidades" }],
    image: "/src/assets/images/queques/menu_general/brigadeiros/brigadeiro-fresa.jpg"
  },
  {
    id: "catering-brigadeiro-fresa-leche-polvo",
    name: "Brigadeiro Fresa y Leche en Polvo",
    description: "Sabor increíble de fresa fresca en almíbar, boleado finamente con leche entera en polvo premium.",
    price: 1100,
    category: "catering",
    subcategory: "brigadeiros",
    presentation: "Brigadeiro",
    minimumOrder: "30 unidades",
    pageNumber: 18,
    rating: 4.9,
    sizes: [{ label: "Brigadeiro", priceAdder: 0, servings: "Mínimo: 30 unidades" }],
    image: "/src/assets/images/queques/menu_general/brigadeiros/brigadeiro-fresa-y-leche-en-polvo.jpg"
  },
  {
    id: "catering-brigadeiro-leche-polvo-nutella",
    name: "Brigadeiro Leche en Polvo con Nutella",
    description: "Masa cremosa e irresistible de leche entera en polvo premium con un suntuoso centro líquido de Nutella de avellanas original.",
    price: 1100,
    category: "catering",
    subcategory: "brigadeiros",
    presentation: "Brigadeiro",
    minimumOrder: "30 unidades",
    pageNumber: 18,
    rating: 5.0,
    sizes: [{ label: "Brigadeiro", priceAdder: 0, servings: "Mínimo: 30 unidades" }],
    image: "/src/assets/images/queques/menu_general/brigadeiros/brigadeiro-leche-en-polvo-con-nutella.jpg"
  },
  {
    id: "catering-brigadeiro-leche-polvo",
    name: "Brigadeiro Leche en Polvo",
    description: "Trufa sedosa elaborada a base de leche condensada y leche entera en polvo premium, con un sabor lácteo exquisitamente dulce.",
    price: 1100,
    category: "catering",
    subcategory: "brigadeiros",
    presentation: "Brigadeiro",
    minimumOrder: "30 unidades",
    pageNumber: 18,
    rating: 4.8,
    sizes: [{ label: "Brigadeiro", priceAdder: 0, servings: "Mínimo: 30 unidades" }],
    image: "/src/assets/images/queques/menu_general/brigadeiros/brigadeiro-leche-en-polvo.jpg"
  },
  {
    id: "catering-brigadeiro-napolitano",
    name: "Brigadeiro Napolitano Fresas, Leche en Polvo y Chocolate",
    description: "Fusión espectacular de tres sabores tradicionales: una esfera tricolor con fresa, leche en polvo y chocolate belga.",
    price: 1100,
    category: "catering",
    subcategory: "brigadeiros",
    presentation: "Brigadeiro",
    minimumOrder: "30 unidades",
    pageNumber: 18,
    rating: 4.9,
    sizes: [{ label: "Brigadeiro", priceAdder: 0, servings: "Mínimo: 30 unidades" }],
    image: "/src/assets/images/queques/menu_general/brigadeiros/brigadeiro-napolitano-fresas-leche-en-polvo-y-chocolate.jpg"
  },
  {
    id: "catering-brigadeiro-fresa-con-chocolate",
    name: "Brigadeiro Fresa con Chocolate",
    description: "Masa cremosa de brigadeiro de fresas frescas boleada a mano y decorada con virutas crujientes de chocolate belga.",
    price: 1100,
    category: "catering",
    subcategory: "brigadeiros",
    presentation: "Brigadeiro",
    minimumOrder: "30 unidades",
    pageNumber: 18,
    rating: 4.9,
    sizes: [{ label: "Brigadeiro", priceAdder: 0, servings: "Mínimo: 30 unidades" }],
    image: "/src/assets/images/queques/menu_general/brigadeiros/brigadeiro-fresa-con-chocolate.jpg"
  },
  {
    id: "catering-brigadeiro-banoffee",
    name: "Brigadeiro Banoffee",
    description: "Inspirado en la famosa tarta: brigadeiro con notas de banano maduro caramelizado, dulce de leche y galleta crujiente.",
    price: 1200,
    category: "catering",
    subcategory: "brigadeiros",
    presentation: "Brigadeiro",
    minimumOrder: "30 unidades",
    pageNumber: 19,
    rating: 4.9,
    sizes: [{ label: "Brigadeiro", priceAdder: 0, servings: "Mínimo: 30 unidades" }],
    image: "/src/assets/images/queques/menu_general/brigadeiros/brigadeiro-banoffee.jpg"
  },
  {
    id: "catering-brigadeiro-baileys",
    name: "Brigadeiro Baileys",
    description: "Elegante y cremoso brigadeiro cocinado con un generoso chorro de licor de crema de whisky irlandés Baileys original.",
    price: 1200,
    category: "catering",
    subcategory: "brigadeiros",
    presentation: "Brigadeiro",
    minimumOrder: "30 unidades",
    pageNumber: 19,
    rating: 5.0,
    sizes: [{ label: "Brigadeiro", priceAdder: 0, servings: "Mínimo: 30 unidades" }],
    image: "/src/assets/images/queques/menu_general/brigadeiros/brigadeiro-baileys.jpg"
  },
  {
    id: "catering-brigadeiro-cafe",
    name: "Brigadeiro Café",
    description: "Sabor refinado de trufa brasileña cocida con un extracto súper concentrado de café espresso costarricense de altura.",
    price: 1200,
    category: "catering",
    subcategory: "brigadeiros",
    presentation: "Brigadeiro",
    minimumOrder: "30 unidades",
    pageNumber: 19,
    rating: 4.9,
    sizes: [{ label: "Brigadeiro", priceAdder: 0, servings: "Mínimo: 30 unidades" }],
    image: "/src/assets/images/queques/menu_general/brigadeiros/brigadeiro-cafe.jpg"
  },
  {
    id: "catering-brigadeiro-chocolate-blanco-baileys-fresa",
    name: "Brigadeiro Chocolate Blanco con Baileys de Fresa",
    description: "Trufa refinada de chocolate blanco belga infusionada con la romántica dulzura del licor Baileys Strawberries & Cream.",
    price: 1200,
    category: "catering",
    subcategory: "brigadeiros",
    presentation: "Brigadeiro",
    minimumOrder: "30 unidades",
    pageNumber: 19,
    rating: 5.0,
    sizes: [{ label: "Brigadeiro", priceAdder: 0, servings: "Mínimo: 30 unidades" }],
    image: "/src/assets/images/queques/menu_general/brigadeiros/brigadeiro-chocolate-blanco-con-baileys-de-fresa.jpg"
  },
  {
    id: "catering-brigadeiro-chocolate-con-relleno-de-fresa-sensacion",
    name: "Brigadeiro Chocolate con Relleno de Fresa Sensación",
    description: "Tarta brasileña de chocolate intenso de cacao belga con un jugoso corazón líquido de jalea coulis de fresas.",
    price: 1200,
    category: "catering",
    subcategory: "brigadeiros",
    presentation: "Brigadeiro",
    minimumOrder: "30 unidades",
    pageNumber: 19,
    rating: 4.9,
    sizes: [{ label: "Brigadeiro", priceAdder: 0, servings: "Mínimo: 30 unidades" }],
    image: "/src/assets/images/queques/menu_general/brigadeiros/brigadeiro-chocolate-con-relleno-de-fresa-sensacion.jpg"
  },
  {
    id: "catering-brigadeiro-maracuya",
    name: "Brigadeiro Maracuyá",
    description: "Perfecta armonía de sabores: la leche condensada suntuosa combinada con la acidez refrescante de pulpa de maracuyá real.",
    price: 1200,
    category: "catering",
    subcategory: "brigadeiros",
    presentation: "Brigadeiro",
    minimumOrder: "30 unidades",
    pageNumber: 19,
    rating: 4.8,
    sizes: [{ label: "Brigadeiro", priceAdder: 0, servings: "Mínimo: 30 unidades" }],
    image: "/src/assets/images/queques/menu_general/brigadeiros/brigadeiro-maracuya.jpg"
  },
  {
    id: "catering-brigadeiro-pistacho-con-granulado-de-pistacho",
    name: "Brigadeiro Pistacho con Granulado de Pistacho",
    description: "Suntuoso brigadeiro gourmet elaborado con auténtica pasta de pistachos importada y boleado en un crujiente granulado de pistacho picado.",
    price: 1200,
    category: "catering",
    subcategory: "brigadeiros",
    presentation: "Brigadeiro",
    minimumOrder: "30 unidades",
    pageNumber: 19,
    rating: 5.0,
    sizes: [{ label: "Brigadeiro", priceAdder: 0, servings: "Mínimo: 30 unidades" }],
    image: "/src/assets/images/queques/menu_general/brigadeiros/brigadeiro-pistacho-con-granulado-de-pistacho.jpg"
  },
  {
    id: "catering-brigadeiro-cheesecake",
    name: "Brigadeiro Cheesecake",
    description: "La reinterpretación del clásico cheesecake en una trufa brasileña de queso crema y mermelada fina de frutos rojos.",
    price: 1200,
    category: "catering",
    subcategory: "brigadeiros",
    presentation: "Brigadeiro",
    minimumOrder: "30 unidades",
    pageNumber: 19,
    rating: 4.8,
    sizes: [{ label: "Brigadeiro", priceAdder: 0, servings: "Mínimo: 30 unidades" }],
    image: "/src/assets/images/queques/menu_general/brigadeiros/brigadeiro-cheesecake.jpg"
  },
  {
    id: "catering-brigadeiro-chocolate-70",
    name: "Brigadeiro Chocolate 70%",
    description: "Para los amantes del cacao puro: brigadeiro elaborado con chocolate belga amargo al 70% de gran profundidad de sabor.",
    price: 1200,
    category: "catering",
    subcategory: "brigadeiros",
    presentation: "Brigadeiro",
    minimumOrder: "30 unidades",
    pageNumber: 19,
    rating: 4.9,
    sizes: [{ label: "Brigadeiro", priceAdder: 0, servings: "Mínimo: 30 unidades" }],
    image: "/src/assets/images/queques/menu_general/brigadeiros/brigadeiro-chocolate-70-porc.jpg"
  },
  {
    id: "catering-brigadeiro-chocolate-con-menta",
    name: "Brigadeiro Chocolate con Menta",
    description: "Elegancia pura. Brigadeiro de chocolate clásico infusionado con esencia natural y refrescante de menta fresca.",
    price: 1200,
    category: "catering",
    subcategory: "brigadeiros",
    presentation: "Brigadeiro",
    minimumOrder: "30 unidades",
    pageNumber: 19,
    rating: 4.9,
    sizes: [{ label: "Brigadeiro", priceAdder: 0, servings: "Mínimo: 30 unidades" }],
    image: "/src/assets/images/queques/menu_general/brigadeiros/brigadeiro-chocolate-con-menta.jpg"
  },

  // --- DULCES ESPECIALES ---
  {
    id: "catering-special-cakepops",
    name: "Cakepops sencillos con color y escarcha",
    description: "Divertidas y deliciosas bolitas de queque mezcladas con frosting y formadas en paleta, decoradas en el color de tu elección y escarcha fina.",
    price: 1800,
    category: "catering",
    subcategory: "dulces_especiales",
    presentation: "Cakepop",
    minimumOrder: "6 por color",
    pageNumber: 20,
    rating: 4.8,
    sizes: [{ label: "Cakepop", priceAdder: 0, servings: "Mínimo: 6 por color" }],
    image: "/src/assets/images/queques/menu_general/dulces_especiales/cakepops-sencillos-con-color-y-escarcha.jpg"
  },
  {
    id: "catering-special-paletas-brownie",
    name: "Paletas de Brownie con color y escarcha",
    description: "Paletas de tierno brownie de la casa bañadas en una cobertura dulce de chocolate de color a elegir y escarcha brillante.",
    price: 2500,
    category: "catering",
    subcategory: "dulces_especiales",
    presentation: "Paleta de brownie",
    minimumOrder: "6 por color",
    pageNumber: 20,
    rating: 4.9,
    sizes: [{ label: "Paleta de brownie", priceAdder: 0, servings: "Mínimo: 6 por color" }],
    image: "/src/assets/images/queques/menu_general/dulces_especiales/paletas-de-brownie-con-color-y-escarcha.jpg"
  },
  {
    id: "catering-special-mini-cupcakes",
    name: "Mini Cupcakes de Red Velvet o Vainilla",
    description: "Pequeños cupcakes de bocado de Red Velvet o vainilla suave, decorados con rosetones de crema o frosting en el color elegido.",
    price: 700,
    category: "catering",
    subcategory: "dulces_especiales",
    presentation: "Mini cupcake",
    minimumOrder: "25 por color y sabor",
    pageNumber: 20,
    rating: 4.7,
    sizes: [{ label: "Mini cupcake", priceAdder: 0, servings: "Mínimo: 25 por color y sabor" }],
    image: "/src/assets/images/queques/menu_general/dulces_especiales/mini-cupcakes-de-red-velvet-o-vainilla.jpg"
  },
  {
    id: "catering-special-cupcakes-rv-cheese",
    name: "Cupcakes de Red Velvet rellenos de Cheese Frosting",
    description: "Cupcakes esponjosos de Red Velvet tradicional de cacao fino, con un corazón untuoso y rico de frosting de queso crema.",
    price: 1800,
    category: "catering",
    subcategory: "dulces_especiales",
    presentation: "Cupcake",
    minimumOrder: "25 unidades",
    pageNumber: 20,
    rating: 4.9,
    sizes: [{ label: "Cupcake", priceAdder: 0, servings: "Mínimo: 25 unidades" }],
    image: "/src/assets/images/queques/menu_general/dulces_especiales/cupcakes-de-red-velvet-rellenos-de-cheese-frosting.jpg"
  },
  {
    id: "catering-special-cupcakes-v-ddl",
    name: "Cupcakes de Vainilla rellenos de dulce de leche",
    description: "Cupcakes tiernos de pura vainilla Bourbon con un corazón denso y generoso de dulce de leche repostero artesanal.",
    price: 1800,
    category: "catering",
    subcategory: "dulces_especiales",
    presentation: "Cupcake",
    minimumOrder: "12 unidades",
    pageNumber: 20,
    rating: 4.8,
    sizes: [{ label: "Cupcake", priceAdder: 0, servings: "Mínimo: 12 unidades" }],
    image: "/src/assets/images/queques/menu_general/dulces_especiales/cupcakes-de-vainilla-rellenos-de-dulce-de-leche.jpg"
  },
  {
    id: "catering-special-paletas-rv-german",
    name: "Paletas de Red Velvet / German Cake con color y escarcha",
    description: "Soberbias paletas de queque Red Velvet o de chocolate tradicional tipo German Cake con coco tostado, decoradas con cobertura de color y escarcha.",
    price: 2500,
    category: "catering",
    subcategory: "dulces_especiales",
    presentation: "Paleta",
    minimumOrder: "6 por color",
    pageNumber: 20,
    rating: 4.9,
    sizes: [{ label: "Paleta", priceAdder: 0, servings: "Mínimo: 6 por color" }],
    image: "/src/assets/images/queques/menu_general/dulces_especiales/paletas-de-red-velvet-german-cake-con-color-y-escarcha.jpg"
  },
  {
    id: "catering-special-paletas-rv-german-premium",
    name: "Paletas de Red Velvet / German Cake con color y escarcha premium",
    description: "Paletas premium súper detalladas con decoraciones de relieve en chocolate, fondant o brillo de lujo y escarcha comestible fina.",
    price: 3000,
    category: "catering",
    subcategory: "dulces_especiales",
    presentation: "Paleta",
    minimumOrder: "6 por color",
    pageNumber: 20,
    rating: 5.0,
    sizes: [{ label: "Paleta", priceAdder: 0, servings: "Mínimo: 6 por color" }],
    image: "/src/assets/images/queques/menu_general/dulces_especiales/paletas-de-red-velvet-german-cake-con-color-y-escarcha-premium.jpg"
  },
  {
    id: "catering-special-petit-four-lemon",
    name: "Petit Four rellenos de Lemon Curd",
    description: "Delicados bocados imperiales de repostería francesa, rellenos con una untuosa e intensa crema untuosa de limón real (lemon curd).",
    price: 1800,
    category: "catering",
    subcategory: "dulces_especiales",
    presentation: "Petit Four",
    minimumOrder: "10 unidades",
    pageNumber: 21,
    rating: 4.9,
    sizes: [{ label: "Petit Four", priceAdder: 0, servings: "Mínimo: 10 unidades" }],
    image: "/src/assets/images/queques/menu_general/dulces_especiales/petit-four-rellenos-de-lemon-curd.jpg"
  },
  {
    id: "catering-special-oreos-covered",
    name: "Chocolate covered oreos con Red Velvet o German Cake",
    description: "Galletas Oreo cubiertas artesanalmente de chocolate belga coloreado y decoradas con relieves o escarcha, rellenas de queque Red Velvet o German.",
    price: 1800,
    category: "catering",
    subcategory: "dulces_especiales",
    presentation: "Oreo cubierta",
    minimumOrder: "6 por color",
    pageNumber: 21,
    rating: 4.8,
    sizes: [{ label: "Oreo cubierta", priceAdder: 0, servings: "Mínimo: 6 por color" }],
    image: "/src/assets/images/queques/menu_general/dulces_especiales/chocolate-covered-oreos-con-red-velvet-o-german-cake.jpg"
  },
  {
    id: "catering-special-shortbread-confites",
    name: "Shortbread Cookies con confites",
    description: "Finísimas y ricas galletas de mantequilla de pastura pura (estilo escocés) decoradas con chispitas y confites festivos de colores.",
    price: 1500,
    category: "catering",
    subcategory: "dulces_especiales",
    presentation: "Galleta shortbread",
    minimumOrder: "20 unidades",
    pageNumber: 21,
    rating: 4.8,
    sizes: [{ label: "Galleta shortbread", priceAdder: 0, servings: "Mínimo: 20 unidades" }],
    image: "/src/assets/images/queques/menu_general/dulces_especiales/shortbread-cookies-con-confites.jpg"
  },
  {
    id: "catering-special-shortbread-moradas",
    name: "Shortbread Cookies moradas con confites",
    description: "Elegante variación de nuestras galletas de mantequilla shortbread teñidas de un color morado lavanda y decoradas con confites selectos.",
    price: 1500,
    category: "catering",
    subcategory: "dulces_especiales",
    presentation: "Galleta shortbread",
    minimumOrder: "20 unidades",
    pageNumber: 21,
    rating: 4.8,
    sizes: [{ label: "Galleta shortbread", priceAdder: 0, servings: "Mínimo: 20 unidades" }],
    image: "/src/assets/images/queques/menu_general/dulces_especiales/shortbread-cookies-moradas-con-confites.jpg"
  },
  {
    id: "catering-special-shortbread-escarcha",
    name: "Shortbread Cookies con escarcha",
    description: "Suntuosas galletas shortbread de pura mantequilla de pastura cubiertas de una delicada y mágica capa de escarcha comestible fina.",
    price: 1500,
    category: "catering",
    subcategory: "dulces_especiales",
    presentation: "Galleta shortbread",
    minimumOrder: "20 unidades",
    pageNumber: 21,
    rating: 4.8,
    sizes: [{ label: "Galleta shortbread", priceAdder: 0, servings: "Mínimo: 20 unidades" }],
    image: "/src/assets/images/queques/menu_general/dulces_especiales/shortbread-cookies-con-escarcha.jpg"
  },
  {
    id: "catering-special-sandwich-shortbread",
    name: "Sandwich de shortbread cookies rellenos de leche condensada",
    description: "Sándwich de dos crujientes galletas shortbread de mantequilla rellenas en su centro de dulce y rica leche condensada cocida.",
    price: 1500,
    category: "catering",
    subcategory: "dulces_especiales",
    presentation: "Sandwich cookie",
    minimumOrder: "20 unidades",
    pageNumber: 21,
    rating: 4.9,
    sizes: [{ label: "Sandwich cookie", priceAdder: 0, servings: "Mínimo: 20 unidades" }],
    image: "/src/assets/images/queques/menu_general/dulces_especiales/sandwich-de-shortbread-cookies-rellenos-de-leche-condensada.jpg"
  },

  // --- MINI GOURMET SALADOS ---
  {
    id: "catering-salado-ceviche-hongos",
    name: "Ceviche de Hongos Frescos con arúgula y queso Grana Padano",
    description: "Refrescante ceviche artesanal de hongos París y Portobello macerados en cítricos, acompañados de arúgula fresca y lajas de queso Grana Padano madurado.",
    price: 2000,
    category: "catering",
    subcategory: "mini_gourmet_salados",
    presentation: "Mini Gourmet salado",
    minimumOrder: "20 unidades",
    pageNumber: 46,
    rating: 4.9,
    sizes: [{ label: "Mini Gourmet salado", priceAdder: 0, servings: "Mínimo: 20 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_salados/mini-gourmet-salados-portada.jpg"
  },
  {
    id: "catering-salado-dip-tomate",
    name: "Dip de Tomate Deshidratado con grissines",
    description: "Cremoso dip elaborado con tomates deshidratados al sol infusionados con hierbas provenzales y aceite de oliva, acompañado de crujientes grissines italianos.",
    price: 2000,
    category: "catering",
    subcategory: "mini_gourmet_salados",
    presentation: "Mini Gourmet salado",
    minimumOrder: "20 unidades",
    pageNumber: 46,
    rating: 4.8,
    sizes: [{ label: "Mini Gourmet salado", priceAdder: 0, servings: "Mínimo: 20 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_salados/mini-gourmet-salados-lista-2000.jpg"
  },
  {
    id: "catering-salado-dip-caviar",
    name: "Dip de Caviar con grissines",
    description: "Lujosa y tersa emulsión batida con hueva fina de esturión selecto y crema agria, servida con finos bastoncitos grissines crujientes.",
    price: 2000,
    category: "catering",
    subcategory: "mini_gourmet_salados",
    presentation: "Mini Gourmet salado",
    minimumOrder: "20 unidades",
    pageNumber: 46,
    rating: 4.9,
    sizes: [{ label: "Mini Gourmet salado", priceAdder: 0, servings: "Mínimo: 20 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_salados/mini-gourmet-salados-lista-2000.jpg"
  },
  {
    id: "catering-salado-dip-tapenade",
    name: "Dip de Tapenade de Atún con mascarpone, aceitunas calamata, alcaparras y pasta de anchoas",
    description: "Intenso dip rústico que equilibra el queso mascarpone suave con tapenade provenzal de atún, aceitunas de Calamata, alcaparras y notas salinas de pasta de anchoa.",
    price: 2000,
    category: "catering",
    subcategory: "mini_gourmet_salados",
    presentation: "Mini Gourmet salado",
    minimumOrder: "20 unidades",
    pageNumber: 46,
    rating: 4.8,
    sizes: [{ label: "Mini Gourmet salado", priceAdder: 0, servings: "Mínimo: 20 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_salados/mini-gourmet-salados-lista-2000.jpg"
  },
  {
    id: "catering-salado-sandwich-roast-beef",
    name: "Mini Sándwich de Roast Beef con aderezo de bluecheese en pan italiano",
    description: "Bocado gourmet en pan italiano rústico horneado relleno con finas lajas de roast beef magro curado en casa y un suntuoso e intenso aderezo de queso azul.",
    price: 2000,
    category: "catering",
    subcategory: "mini_gourmet_salados",
    presentation: "Mini Gourmet salado",
    minimumOrder: "20 unidades",
    pageNumber: 46,
    rating: 4.9,
    sizes: [{ label: "Mini Gourmet salado", priceAdder: 0, servings: "Mínimo: 20 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_salados/mini-gourmet-salados-lista-2000.jpg"
  },
  {
    id: "catering-salado-sandwich-pollo",
    name: "Mini Sándwich de Pollo con aderezo de albahaca en pan italiano",
    description: "Tierno pollo mechado cocinado a baja temperatura combinado con un aromático aderezo pesto-crema de albahaca fresca en pan italiano rústico.",
    price: 2000,
    category: "catering",
    subcategory: "mini_gourmet_salados",
    presentation: "Mini Gourmet salado",
    minimumOrder: "20 unidades",
    pageNumber: 46,
    rating: 4.8,
    sizes: [{ label: "Mini Gourmet salado", priceAdder: 0, servings: "Mínimo: 20 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_salados/mini-gourmet-salados-lista-2000.jpg"
  },
  {
    id: "catering-salado-sandwich-tartine",
    name: "Mini Sándwich de Tartine de huevo con salmón ahumado",
    description: "Elegante bocado abierto de ensalada de huevo mimosa cremosa coronado con un fino doblez de salmón ahumado importado y eneldo fresco.",
    price: 2000,
    category: "catering",
    subcategory: "mini_gourmet_salados",
    presentation: "Mini Gourmet salado",
    minimumOrder: "20 unidades",
    pageNumber: 46,
    rating: 4.9,
    sizes: [{ label: "Mini Gourmet salado", priceAdder: 0, servings: "Mínimo: 20 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_salados/mini-gourmet-salados-lista-2000.jpg"
  },
  {
    id: "catering-salado-sandwich-olaf",
    name: "Mini Sándwich Olaf en pan italiano con atún, pasta de caviar y aderezo especial",
    description: "Sándwich de autor en pan italiano suave con relleno de ensalada fina de atún, pasta de caviar untuosa y aderezo secreto de la casa.",
    price: 2000,
    category: "catering",
    subcategory: "mini_gourmet_salados",
    presentation: "Mini Gourmet salado",
    minimumOrder: "20 unidades",
    pageNumber: 46,
    rating: 4.8,
    sizes: [{ label: "Mini Gourmet salado", priceAdder: 0, servings: "Mínimo: 20 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_salados/mini-gourmet-salados-lista-2000.jpg"
  },
  {
    id: "catering-salado-ensalada-fiesta",
    name: "Ensalada Fiesta Mexicana con tomates cherry, aguacate, cebolla morada y vinagreta especial",
    description: "Fresquísima y colorida ensalada servida en porción individual con tomates cherry, cubitos de aguacate cremoso, cebolla morada y una vinagreta especial de cilantro.",
    price: 2000,
    category: "catering",
    subcategory: "mini_gourmet_salados",
    presentation: "Mini Gourmet salado",
    minimumOrder: "20 unidades",
    pageNumber: 46,
    rating: 4.8,
    sizes: [{ label: "Mini Gourmet salado", priceAdder: 0, servings: "Mínimo: 20 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_salados/mini-gourmet-salados-lista-2000.jpg"
  },
  {
    id: "catering-salado-ensalada-feta",
    name: "Ensalada de queso feta con sandía, menta y vinagreta especial",
    description: "El maridaje mediterráneo definitivo: cubos jugosos de sandía fría, queso feta desmoronado, menta fresca del jardín y vinagreta aromática de champagne.",
    price: 2000,
    category: "catering",
    subcategory: "mini_gourmet_salados",
    presentation: "Mini Gourmet salado",
    minimumOrder: "20 unidades",
    pageNumber: 46,
    rating: 4.9,
    sizes: [{ label: "Mini Gourmet salado", priceAdder: 0, servings: "Mínimo: 20 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_salados/mini-gourmet-salados-lista-2000.jpg"
  },
  {
    id: "catering-salado-cus-cus",
    name: "Cus Cus especial con salsa de yogurt natural y curry",
    description: "Semillas de sémola de trigo esponjosas, sazonadas con pasas y almendras, aderezadas con una exótica salsa fresca de yogurt natural y curry de Madras.",
    price: 2000,
    category: "catering",
    subcategory: "mini_gourmet_salados",
    presentation: "Mini Gourmet salado",
    minimumOrder: "30 unidades",
    pageNumber: 46,
    rating: 4.8,
    sizes: [{ label: "Mini Gourmet salado", priceAdder: 0, servings: "Mínimo: 30 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_salados/mini-gourmet-salados-lista-2000.jpg"
  },
  {
    id: "catering-salado-cheddar-scones",
    name: "Cheddar Dill Scones",
    description: "Scones ingleses salados horneados artesanalmente con queso cheddar añejo de gran carácter y finas ramitas de eneldo fresco.",
    price: 2000,
    category: "catering",
    subcategory: "mini_gourmet_salados",
    presentation: "Mini Gourmet salado",
    minimumOrder: "30 unidades",
    pageNumber: 46,
    rating: 4.9,
    sizes: [{ label: "Mini Gourmet salado", priceAdder: 0, servings: "Mínimo: 30 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_salados/mini-gourmet-salados-lista-2000.jpg"
  },
  {
    id: "catering-salado-montadito-pepino",
    name: "Montadito de pepino con mantequilla de champagne en pan italiano",
    description: "Elegante canapé de rodajas finas de pepino sobre una lujosa y batida mantequilla batida con champagne en pan de miga italiano.",
    price: 2000,
    category: "catering",
    subcategory: "mini_gourmet_salados",
    presentation: "Mini Gourmet salado",
    minimumOrder: "30 unidades",
    pageNumber: 46,
    rating: 4.7,
    sizes: [{ label: "Mini Gourmet salado", priceAdder: 0, servings: "Mínimo: 30 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_salados/mini-gourmet-salados-lista-2000.jpg"
  },
  {
    id: "catering-salado-datiles-tocineta",
    name: "Dátiles rellenos con queso de cabra y almendra, envueltos en tocineta",
    description: "Bocado sublime de dátiles medjool maduros rellenos de queso de cabra cremoso y una almendra tostada entera, envueltos en tocineta ahumada y horneados.",
    price: 2000,
    category: "catering",
    subcategory: "mini_gourmet_salados",
    presentation: "Mini Gourmet salado",
    minimumOrder: "30 unidades",
    pageNumber: 46,
    rating: 5.0,
    sizes: [{ label: "Mini Gourmet salado", priceAdder: 0, servings: "Mínimo: 30 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_salados/mini-gourmet-salados-lista-2000.jpg"
  },
  {
    id: "catering-salado-tartaletas-pollo",
    name: "Tartaletas de Pollo Veroniq",
    description: "Minúsculas tartaletas de hojaldre rellenas de nuestra ensalada exclusiva de pollo mechado, almendras tostadas crujientes, uvas verdes cortadas y apio fino.",
    price: 2000,
    category: "catering",
    subcategory: "mini_gourmet_salados",
    presentation: "Mini Gourmet salado",
    minimumOrder: "30 unidades",
    pageNumber: 46,
    rating: 4.9,
    sizes: [{ label: "Mini Gourmet salado", priceAdder: 0, servings: "Mínimo: 30 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_salados/mini-gourmet-salados-lista-2000.jpg"
  },
  {
    id: "catering-salado-ensalada-pollo-dijon",
    name: "Ensalada de Pollo con aderezo de mostaza Dijon, brócoli y tomates cherry",
    description: "Ensalada tibia o fría servida individualmente, con trozos de pollo a la plancha, arbolitos de brócoli al dente, tomates cherry y aderezo emulsionado de Dijon.",
    price: 2000,
    category: "catering",
    subcategory: "mini_gourmet_salados",
    presentation: "Mini Gourmet salado",
    minimumOrder: "30 unidades",
    pageNumber: 46,
    rating: 4.8,
    sizes: [{ label: "Mini Gourmet salado", priceAdder: 0, servings: "Mínimo: 30 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_salados/mini-gourmet-salados-lista-2000.jpg"
  },
  {
    id: "catering-salado-pasta-vegetales",
    name: "Pasta con vegetales rostizados, queso feta y albahaca",
    description: "Pasta penne corta salteada con vegetales al horno (calabacín, pimiento, cebolla) sazonados con hierbas, queso feta desmoronado y hojas de albahaca.",
    price: 2000,
    category: "catering",
    subcategory: "mini_gourmet_salados",
    presentation: "Mini Gourmet salado",
    minimumOrder: "30 unidades",
    pageNumber: 46,
    rating: 4.8,
    sizes: [{ label: "Mini Gourmet salado", priceAdder: 0, servings: "Mínimo: 30 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_salados/mini-gourmet-salados-lista-2000.jpg"
  },
  {
    id: "catering-salado-ensalada-waldorf",
    name: "Ensalada Waldorf con manzana, apio, nueces y aderezo especial",
    description: "Nuestra adaptación gourmet de la clásica ensalada: rodajas de manzana verde ácida, ramitas de apio tierno, nueces pecanas y aderezo cremoso ligero.",
    price: 2000,
    category: "catering",
    subcategory: "mini_gourmet_salados",
    presentation: "Mini Gourmet salado",
    minimumOrder: "30 unidades",
    pageNumber: 46,
    rating: 4.8,
    sizes: [{ label: "Mini Gourmet salado", priceAdder: 0, servings: "Mínimo: 30 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_salados/mini-gourmet-salados-lista-2000.jpg"
  },
  {
    id: "catering-salado-potato-salad",
    name: "Old Fashioned Potato Salad con papa, eneldo y semillas de mostaza Dijon",
    description: "Ensalada de papa rústica tradicional con trocitos de eneldo fresco de aroma excepcional y granos enteros crujientes de mostaza Dijon.",
    price: 2000,
    category: "catering",
    subcategory: "mini_gourmet_salados",
    presentation: "Mini Gourmet salado",
    minimumOrder: "30 unidades",
    pageNumber: 46,
    rating: 4.8,
    sizes: [{ label: "Mini Gourmet salado", priceAdder: 0, servings: "Mínimo: 30 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_salados/mini-gourmet-salados-lista-2000.jpg"
  },
  {
    id: "catering-salado-tomates-cherry",
    name: "Tomates Cherry con queso feta y vinagreta de champagne",
    description: "Vistosos vasitos de ensalada fría con tomates cherry dulces enteros, perlas de queso feta y una emulsionada y fina vinagreta de champagne.",
    price: 2000,
    category: "catering",
    subcategory: "mini_gourmet_salados",
    presentation: "Mini Gourmet salado",
    minimumOrder: "30 unidades",
    pageNumber: 46,
    rating: 4.8,
    sizes: [{ label: "Mini Gourmet salado", priceAdder: 0, servings: "Mínimo: 30 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_salados/mini-gourmet-salados-lista-2000.jpg"
  },
  {
    id: "catering-salado-ceviche-pejibaye",
    name: "Ceviche de Pejibaye con Palmito",
    description: "Ceviche nacional de autor con cubitos de pejibaye tierno cocinado, palmito fresco crujiente, jugos cítricos y cebollino.",
    price: 2000,
    category: "catering",
    subcategory: "mini_gourmet_salados",
    presentation: "Mini Gourmet salado",
    minimumOrder: "30 unidades",
    pageNumber: 46,
    rating: 4.9,
    sizes: [{ label: "Mini Gourmet salado", priceAdder: 0, servings: "Mínimo: 30 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_salados/mini-gourmet-salados-lista-2000.jpg"
  },
  {
    id: "catering-salado-pollo-veroniq",
    name: "Pollo Veroniq con pollo, almendras, uvas verdes y apio",
    description: "Fina ensalada cremosa para untar o disfrutar sola con pechuga de pollo deshebrada, trozos de almendra, uvas frescas y apio tierno.",
    price: 2000,
    category: "catering",
    subcategory: "mini_gourmet_salados",
    presentation: "Mini Gourmet salado",
    minimumOrder: "30 unidades",
    pageNumber: 46,
    rating: 4.9,
    sizes: [{ label: "Mini Gourmet salado", priceAdder: 0, servings: "Mínimo: 30 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_salados/mini-gourmet-salados-lista-2000.jpg"
  },
  {
    id: "catering-salado-pasta-fria",
    name: "Pasta Fría con mozzarella fresca, tomates cherry y albahaca",
    description: "Ensalada italiana clásica de pasta fusilli corta servida fría con bolitas de mozzarella fresca boconccini, tomates cherry dulces y aderezo de albahaca.",
    price: 2000,
    category: "catering",
    subcategory: "mini_gourmet_salados",
    presentation: "Mini Gourmet salado",
    minimumOrder: "30 unidades",
    pageNumber: 46,
    rating: 4.8,
    sizes: [{ label: "Mini Gourmet salado", priceAdder: 0, servings: "Mínimo: 30 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_salados/mini-gourmet-salados-lista-2000.jpg"
  },
  {
    id: "catering-salado-sandwich-salmon-brioche",
    name: "Mini Sándwich de Salmón Ahumado en pan brioche con aderezo de eneldo",
    description: "Delicado pan de brioche francés dulce untado con mantequilla fina y relleno con láminas selectas de salmón ahumado importado y una emulsión suave de eneldo.",
    price: 3500,
    category: "catering",
    subcategory: "mini_gourmet_salados",
    presentation: "Mini Gourmet salado",
    minimumOrder: "20 unidades",
    pageNumber: 47,
    rating: 5.0,
    sizes: [{ label: "Mini Gourmet salado", priceAdder: 0, servings: "Mínimo: 20 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_salados/mini-gourmet-salados-lista-3500.jpg"
  },
  {
    id: "catering-salado-ensalada-langosta",
    name: "Ensalada de pasta con Langosta",
    description: "Suntuosos vasitos gourmet individuales con ensalada fresca de pasta corta enriquecida con tierna y jugosa pulpa de langosta del Caribe y aderezo suave.",
    price: 3500,
    category: "catering",
    subcategory: "mini_gourmet_salados",
    presentation: "Mini Gourmet salado",
    minimumOrder: "20 unidades",
    pageNumber: 47,
    rating: 5.0,
    sizes: [{ label: "Mini Gourmet salado", priceAdder: 0, servings: "Mínimo: 20 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_salados/mini-gourmet-salados-lista-3500.jpg"
  },
  {
    id: "catering-salado-ensalada-camarones",
    name: "Ensalada de Camarones con eneldo y naranja",
    description: "Camarones del Pacífico escalfados a la perfección combinados con gajos de naranja dulce y un refrescante aderezo emulsionado de eneldo fresco.",
    price: 3500,
    category: "catering",
    subcategory: "mini_gourmet_salados",
    presentation: "Mini Gourmet salado",
    minimumOrder: "20 unidades",
    pageNumber: 47,
    rating: 5.0,
    sizes: [{ label: "Mini Gourmet salado", priceAdder: 0, servings: "Mínimo: 20 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_salados/mini-gourmet-salados-lista-3500.jpg"
  },
  {
    id: "catering-salado-sandwich-salmon-italiano",
    name: "Mini Sándwich de Salmón Ahumado en pan italiano con aderezo de eneldo",
    description: "Pan de miga italiano rústico horneado lentamente, relleno con dobleces de salmón ahumado escandinavo selecto y nuestro aderezo cremoso de eneldo fresco.",
    price: 3500,
    category: "catering",
    subcategory: "mini_gourmet_salados",
    presentation: "Mini Gourmet salado",
    minimumOrder: "20 unidades",
    pageNumber: 47,
    rating: 4.9,
    sizes: [{ label: "Mini Gourmet salado", priceAdder: 0, servings: "Mínimo: 20 unidades" }],
    image: "/src/assets/images/queques/menu_general/mini_gourmet_salados/mini-gourmet-salados-lista-3500.jpg"
  }
];
